### ISSUE TITLE
Frontend filtering does not work for empty value of County Code

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-ong#144]
When loading the answers, the county code filtering field is empty.
The query sent to the backend contains the countyCode variable as the "null" string, not a null variable. This is propagated to the database layer and no information is returned to the frontend.

The countyCode variable should be an empty string when no information is added to the filtering component.

**Comment by idormenco** [comment]
@RaduCStefanescu i can handle this. Where ui is located :)

**Comment by RaduCStefanescu** [comment]
In progress @idormenco
