### ISSUE TITLE
Filtering component should be done inline

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-ong#145]
Currently the filtering component is very basic. We need to component to at least be inline.
This is the component currently:

<img width="415" alt="Screenshot 2019-10-10 at 10 50 27" src="https://user-images.githubusercontent.com/15039873/66549846-df6cc480-eb4c-11e9-8842-13f349f3f626.png">

**Comment by idormenco** [comment]
I will handle this

**Comment by RaduCStefanescu** [comment]
In progress @idormenco
