### ISSUE TITLE
Update frontend to use environments

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-ong#149]
Currently loading the backend env for the API is done by editing the `proxy.conf.json` file.
We should be able to use environments for this type of deployments.

More information can be found here:
https://blog.angulartraining.com/how-to-manage-different-environments-with-angular-cli-883c26e99d15

**Comment by idormenco** [comment]
I will work on this

**Comment by RaduCStefanescu** [comment]
In progress @idormenco
