### ISSUE TITLE
Connect current frontend to new API

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-ong#150]
The new API can be found at this URL
https://mv-mobile-test.azurewebsites.net/swagger/index.html

The current calls done on the backend should be done to the new API.

**Comment by paul-antal** [comment]
I'm working on it

**Comment by RaduCStefanescu** [comment]
In progress @paul-antal

**Comment by RaduCStefanescu** [comment]
Fixed in #153
