### ISSUE TITLE
Remove api from current repo

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-ong#152]
The API developed in the current repo is being migrated to 
https://github.com/code4romania/monitorizare-vot/tree/refactor/major-wip

The folder `https://github.com/code4romania/monitorizare-vot-ong/tree/master/api/MonitorizareVot.Ong` should be removed from the current repository.

**Comment by paul-antal** [comment]
I can take that one

**Comment by paul-antal** [comment]
Already did with this one 
https://github.com/code4romania/monitorizare-vot-ong/pull/154

**Comment by RaduCStefanescu** [comment]
I am going to leave this one open just a little bit to make sure we did not miss anything in the migration to the new API.
