### ISSUE TITLE
[Push Notifications] Changes on Push Notifications feature

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-ong#159]
This issue is referring to this PR that is open on the Push Notification feature
https://github.com/code4romania/monitorizare-vot-ong/pull/158

The feature needs a few more changes:
- for the filtering part, we are going to stick with Counties and Polling Station numbers on those counties - for this please use this endpoint: `/api/v1/polling-station` that returns the max number of polling stations per county
- the feature needs to display all the active observers in those polling stations, using this endpoint: `/api/v1/observer/active` and the Observer component already defined by the Observer feature
- the user can select or deselect from the list of observers, and after can send the message - we need to use the `/api/v1/notification/send` endpoint
- the recipients array from the json sent to `/api/v1/notification/send` will hold a list of selected observer ids
- add a input field for the title of the notification

**Comment by idormenco** [comment]
I am on it

**Comment by RaduCStefanescu** [comment]
Fixed by #171
