### ISSUE TITLE
[Observers] Display total number of Observers

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-ong#160]
The observers page needs to display the correct number of observers, retrieved from the backend.
This is linked to https://github.com/code4romania/monitorizare-vot/issues/162

**Comment by aniri** [comment]
Implemented in BE as GET `/api/v1/observer/count`

**Comment by idormenco** [comment]
i will try this

**Comment by RaduCStefanescu** [comment]
In progress @idormenco

**Comment by RaduCStefanescu** [comment]
Fixed in #168 
Can be closed
