### ISSUE TITLE
Observers saved through frontend have undefined password

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-ong#172]
When saving a new Observer manually from the frontend, using Add Observer feature, end up having `undefined` password in database.
The request coming from frontend seems to be incorrect:
`https://mv-mobile-test.azurewebsites.net/api/v1/observer?Phone=0788998899&Pin=undefined&Name=Test%20User&SendSMS=false`

**Comment by idormenco** [comment]
done

**Comment by RaduCStefanescu** [comment]
Fixed by #173
