### ISSUE TITLE
Display form description instead of Form 1

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-ong#175]
The frontend should display the form description, and not Form 1 when displaying answers and emergencies.
<img width="436" alt="Screenshot 2019-11-05 at 09 48 12" src="https://user-images.githubusercontent.com/15039873/68188250-6af13e00-ffb1-11e9-8a2c-81e6bb100a6e.png">

**Comment by idormenco** [comment]
on it

**Comment by RaduCStefanescu** [comment]
Fixed in #177
