### ISSUE TITLE
Add PIN entry for "Reset password" feature

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-ong#179]
As part of the reset password feature we need to add a text entry where the user can add the new password for the account.
This issue is related to: https://github.com/code4romania/monitorizare-vot/issues/215

**Comment by idormenco** [comment]
on it

**Comment by RaduCStefanescu** [comment]
In progress @idormenco

**Comment by idormenco** [comment]
@RaduCStefanescu please close this issue

**Comment by aniri** [comment]
closing this as it was fixed in https://github.com/code4romania/monitorizare-vot-ong/pull/181
