### ISSUE TITLE
Add "Download answers" button to the Answers tab

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-ong#180]
In order to be able to provide all answers to NGOs, we need to provide a simple way to download the answers.
Currently the backend has been enhanced with a new endpoint: `/api/v1/export/all`
We need a simple button on the Answers tab that does a simple GET on that endpoint.

**Comment by bvizureanu** [comment]
the endpoind should return a file and ideally the user will not have to navigate away from the current page in order to download the file

**Comment by damianr13** [comment]
- We will use existing fields + any other more that are needed
- Add a second button for getting the data
- There will be a confirmation dialog before the call to the endpoint

**Comment by damianr13** [comment]
Solved and submitted pull request: #188

**Comment by idormenco** [comment]
@RaduCStefanescu can we close it

**Comment by RaduCStefanescu** [comment]
yes we can!
Closed by #188
