### ISSUE TITLE
Sorted by: “Last login – Ascending” redirects

### ISSUE THREAD

**Issue by gepaltineanu** [code4romania/monitorizare-vot-ong#184]
In the Observers tab -> sorted by: clicking on “Last login – Ascending” redirects to the Emergencies tab.

**Comment by damianr13** [comment]
I removed the redirect for now, but based on swagger I don't think that the backend knows how to sort observers by last login

**Comment by idormenco** [comment]
@damianr13 for now backend does not know how to sort. @aniri can you add an issue on backend part to support this feature
