### ISSUE TITLE
Update the display of the observer tile in the observers page to match the one from the notifications page

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#198]
We should have consistent design for tiles. Please update the observer tile in the observers page to match the change in PR https://github.com/code4romania/monitorizare-vot-ong/pull/195

- the selected checkbox should be in the top right corner
- the tile should be selected / deselected when the whole tile is clicked, not only the small circle

**Comment by idormenco** [comment]
Will do
