### ISSUE TITLE
Datele din formular disponibil trebuie expuse in API

### ISSUE THREAD

**Issue by dhont** [code4romania/monitorizare-vot-ong#20]
Ca Admin ONG , cand accesez o sesizare din lista de sesizari sau urgente vreau sa vad deasupra tab-urilor informatiile despre sesizare (ora sosirii, ora plecarii, BESV, etc)

**Comment by Lidiadev** [comment]
Endpoint pentru raspunsuri formular:

- GET api/v1/raspunsuri/RaspunsuriFormular

**Comment by Lidiadev** [comment]
Actualizat endpoint-ul sa primeasca ObserverId and SectionId in loc de IdObservator si IdSectieDeVotare
