### ISSUE TITLE
Statistics tab not loading

### ISSUE THREAD

**Issue by gepaltineanu** [code4romania/monitorizare-vot-ong#207]
The statistics tab does not load. The link I used is:
https://app.votemonitor.org/statistics

![statistics](https://user-images.githubusercontent.com/56204138/73591266-09c80080-44f5-11ea-8c33-a2ebcfcd05c8.png)

**Comment by aniri** [comment]
closing this as it was not yet implemented. will be covered by these issues https://github.com/code4romania/monitorizare-vot-ong/issues?q=is%3Aissue+is%3Aopen+reports
