### ISSUE TITLE
[Notifications] Update notifications page to new UI

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#210]
New UI is available here: https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=754%3A0

- [ ] update to new UI elements 
- [ ] by default, notifications should be sent to all observers
- [ ] filtering should be done by county and polling station numbers (a range of numbers)
- [ ] the number of observers is shown live in the CTA button and in the filter section after applying filters
- [ ] the send notification call to action button text changes after filtering

Please use bootstrap classes as much as possible and avoid adding custom css styles to keep the codebase clean & consistent. The new UI should be as similar as possible to the one in figma, not pixel perfect.

Also, make sure all texts are extracted in translation files.

**Comment by aniri** [comment]
Here's a preview of how it should look like:

![notifications](https://user-images.githubusercontent.com/1358055/74771792-771ab600-5297-11ea-96e1-e0d6561567a1.JPG)

**Comment by nicolaes** [comment]
Starting work on this.
