### ISSUE TITLE
[Notifications] Show notifications history

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#218]
Depends on https://github.com/code4romania/monitorizare-vot-ong/issues/210

New endpoint: `GET ​/api​/v1​/notification​/get​/all`

New UI is available here: https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=754%3A0

- [ ] add notification history button in the notifications page 
- [ ] add page for viewing notifications history
- [ ] display notifications in a paginated list
- [ ] for each notification show in the table: sender name, name of the ngo, notification title, notification text and inserted at datetime
- [ ] notifications filtering can be ignored for now

![Capture](https://user-images.githubusercontent.com/1358055/75096888-c10fde80-55ac-11ea-93e2-22d3305dd042.JPG)

_Please use bootstrap classes as much as possible and avoid adding custom css styles to keep the codebase clean & consistent. The new UI should be as similar as possible to the one in figma, not pixel perfect.

Also, make sure all texts are extracted in translation files._

**Comment by nicolaes** [comment]
Starting work on this.
