### ISSUE TITLE
[Observers] Add / edit / delete observer - update to new UI

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#225]
**Depends on** https://github.com/code4romania/monitorizare-vot-ong/issues/224

UI is available here (make it as similar as possible to the new one): https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=754%3A0

- [ ] new button for adding an observer 
- [ ] add a new page for adding / editing observer details
- [ ] add the available actions button&dropdown in the observer list - available actions are edit, delete, reset password and send notification

Please use bootstrap classes as much as possible and avoid adding custom css styles to keep the codebase clean & consistent. The new UI should be as similar as possible to the one in figma, not pixel perfect.

Also, make sure all texts are extracted in translation files.

**Comment by Andrei0872** [comment]
I'd be glad to start working on this.
