### ISSUE TITLE
[Observers] Add the possibility of sending notifications from the observers screen

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#227]
Depends on https://github.com/code4romania/monitorizare-vot-ong/issues/224

Add the option to send a notification to an observer directly from the observers list.

Also add the option to select more observers from the list and send the notification to all of them.

When clicking the send notification option, the user should be redirected to the send notification screen with pre selected observers list.

UI updates needed to the send notifications screen in this case.

UI available here: https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=754%3A0

**Comment by nicolaes** [comment]
Starting work on this.
