### ISSUE TITLE
[UI] Update login screen to new UI

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#233]
The new UI can be found here: https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=754%3A0

**Comment by Botosio** [comment]
I can take this one @aniri , Can you add the Hacktoberfest label too please.

**Comment by Botosio** [comment]
@aniri do you have a better (bigger) icon image???
Halfway done with this.

![image](https://user-images.githubusercontent.com/44526601/95580527-7c369c00-0a05-11eb-9bf6-1fa888eaaffc.png)

**Comment by Botosio** [comment]
@aniri I changed the body color, this will affect the rest of the app. let me know if we should do this or not.  All of the mockups has a darker background than #fff.

![image](https://user-images.githubusercontent.com/44526601/95582092-20b9dd80-0a08-11eb-964f-05d287fd32fb.png)

**Comment by aniri** [comment]
> @aniri I changed the body color, this will affect the rest of the app. let me know if we should do this or not.  All of the mockups has a darker background than #fff.
> 
> ![image](https://user-images.githubusercontent.com/44526601/95582092-20b9dd80-0a08-11eb-964f-05d287fd32fb.png)
> 

@Botosio it looks great! yes, it's ok to change the background color for the whole app :D I don't have a bigger icon now, but that can be changed later if needed. Thanks for your help!
