### ISSUE TITLE
Update dependency versions

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#235]
- Upgrade minimist to version 0.2.1 or later.
- Upgrade lodash to version 4.17.12 or later.
- Upgrade lodash.template to version 4.5.0 or later.
- Upgrade kind-of to version 6.0.3 or later. 
- Upgrade set-value to version 2.0.1 or later. 
- Upgrade minimatch to version 3.0.2 or later.

**Comment by Utwo** [comment]
I can take this

**Comment by Utwo** [comment]
We can close this :+1:
