### ISSUE TITLE
Integrate forms components from case file project

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#245]
- add a new menu entry - forms
- reuse as much of the code as possible from https://github.com/code4romania/case-file-web
- needed functionality:
    - view forms list
    - add new form
    - edit form (not yet implemented in case file, it is in progress)
    - delete form (not yet implemented in case file, it is in progress)
- adjust data model in order to be aligned with MV data model - https://app-vmon-api-dev.azurewebsites.net/swagger/index.html
- add functionality for missing question types, the ones in MV are:
```
QuestionTypes
0 - multiple choice
1 - single choice
2 - single choice + free text
3 - multiple choice + free text
```
* Please focus mainly on functionality and not design issues, but keep in mind that this will be the final MV design: https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=1095%3A688

**Comment by damianr13** [comment]
I am working on this issue

**Comment by RaduCStefanescu** [comment]
All yours @damianr13
