### ISSUE TITLE
[BUG] Filtering observers not working on notification page

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#252]
- go to notifications page
- select county
- select polling station interval
- press `search`
- expected behaviour is to call the `/api/v1/observer/active` with all selected info filled in

- current behaviour: the polling station numbers show up as undefined `/api/v1/observer/active?countyCodes=B&fromPollingStationNumber=undefined&toPollingStationNumber=undefined&currentlyCheckedIn=true`

**Comment by jrstrayhorn** [comment]
I'd like to work on this!

**Comment by RaduCStefanescu** [comment]
All yours @jrstrayhorn
