### ISSUE TITLE
Add loader for download answers action

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#257]
- go to answers page
- press the `download answers` button
- if there are many answers in db, it takes some time to download them, a loader would be useful :smiley:

**Comment by neeleshbisht99** [comment]
I am into React, never worked with Angular. But let me know, if I can do this ?

**Comment by aniri** [comment]
@neeleshbisht99 you can try, of course :) and send a PR :)

**Comment by aamanunin** [comment]
@aniri Hi, cant go to Answer page, help me why? I run ng serve and go to localhost
