### ISSUE TITLE
[Forms] Update forms list page to new UI

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#265]
Please see the new UI here https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=1125%3A1003 under the `Forms` header.

Updates to be made to the current implementation:
- add tabs for Public / Draft forms (the endpoint for filtering forms by draft flag will be implemented here https://github.com/code4romania/monitorizare-vot/issues/298 , but you can assume that it is `/api/v1/form?draft=true` )
- styling
- there is no need to add pagination to the list

![create form - add new form section](https://user-images.githubusercontent.com/1358055/95119904-6307c400-0755-11eb-8c07-914cebf3d7a2.png)

**Comment by Armagedon0097** [comment]
I'll take this if possible xD
