### ISSUE TITLE
[Forms] Add the possibility for flagging answers

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#266]
Please see the new UI here, under Create form https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=1125%3A1003

Add the flag icon to answer options, similar to the free text one:
![option](https://user-images.githubusercontent.com/1358055/95120628-867f3e80-0756-11eb-812d-97d3437037be.png)

If pressed, the corresponding option should have the `flagged` value set to true.

**Comment by jrstrayhorn** [comment]
I'd like to work on this one!

**Comment by jrstrayhorn** [comment]
does this depend on the new UI being completed first #268 ?

**Comment by aniri** [comment]
@jrstrayhorn it can also be done on the old UI, as we need this as a feature :smiley:

**Comment by jrstrayhorn** [comment]
got it!  I'll start working on it!! Thanks!
