### ISSUE TITLE
[Forms] Add tool tips for option icons

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#267]
The new UI could be seen here https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=1120%3A31

Please add tool tip to the two icons that can show up for answers:
- isFreeText - text should be `Mark as free text` / `Mark as regular`
- isFlagged - text should be `Flag option` / `Unflag option`

![create form - edit form - tooltip if needed](https://user-images.githubusercontent.com/1358055/95121326-92b7cb80-0757-11eb-86e4-af5581c5660a.png)

**Comment by ajeurkar** [comment]
@aniri Could you please assign this to me?

**Comment by ajeurkar** [comment]
@aniri Do I need to setup the backend as well? Since I cannot login to app locally.

**Comment by aniri** [comment]
@ajeurkar please use the test / test2020 credentials to login.

**Comment by ajeurkar** [comment]
@aniri This is dependent on #266. Since the flag option is yet to be added. :)

**Comment by aniri** [comment]
@ajeurkar #266 was just closed ;)
