### ISSUE TITLE
[Forms] Update form view to new UI

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#268]
Please see the new UI here under Create form: https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=1120%3A31

**Comment by Botosio** [comment]
Hello, @aniri I was looking to help out with this one?

**Comment by aniri** [comment]
> Hello, @aniri I was looking to help out with this one?

@Botosio sure :D

**Comment by Botosio** [comment]
Thanks, do you assign it to me so no one else picks it up or it doesn't matter?

**Comment by Botosio** [comment]
Thank you!

**Comment by Botosio** [comment]
Creating PR soon, anything off? @aniri 
![image](https://user-images.githubusercontent.com/44526601/95378887-9318a980-08b2-11eb-93f1-01011c6aefb2.png)

**Comment by Botosio** [comment]
Updated screenshot.
![image](https://user-images.githubusercontent.com/44526601/95456221-023ae000-093d-11eb-855b-508ec4788746.png)

**Comment by Botosio** [comment]
Sorry one more thing, @aniri , this looks like 2 controls in 1???  I didn't touch this part of the app.
![image](https://user-images.githubusercontent.com/44526601/95456418-47f7a880-093d-11eb-8705-d56988f528eb.png)

**Comment by aniri** [comment]
@Botosio yes, I will add that as an extra issue for improvement. As it's just a nice-to-have from the design. I'll merge your PR, thanks a lot for your help!

**Comment by Botosio** [comment]
@aniri sounds good.  If you wanted to create a new issue on the forms page about padding (gutter space), I can take that one on and test the responsiveness of the form too for a smaller device.

**Comment by aniri** [comment]
@Botosio thanks for the ideas! I've added the two low priority issues ;)

https://github.com/code4romania/monitorizare-vot-ong/issues/279
https://github.com/code4romania/monitorizare-vot-ong/issues/280
