### ISSUE TITLE
[Stats] Update statistics page to new UI

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#284]
Adapt the UI for the statistics page to make it as similar as possible to the one here https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=754%3A0 under Reports. 

Please use bootstrap classes as much as possible and avoid adding custom css styles to keep the codebase clean & consistent.

Also, make sure all texts are extracted in translation files. 

![Screenshot from 2020-10-13 11-28-18](https://user-images.githubusercontent.com/1358055/95835915-7f07f880-0d47-11eb-9d48-f5c1b1a90f84.png)

![Screenshot from 2020-10-13 11-12-57](https://user-images.githubusercontent.com/1358055/95835919-80d1bc00-0d47-11eb-9856-c261922efdbb.png)

**Comment by Botosio** [comment]
@aniri want me to take a look?

**Comment by Botosio** [comment]
Also are we branching from upstream/develop or origin/develop? (If it matters?)

**Comment by Botosio** [comment]
@aniri I'm not seeing any data coming back on this page.
https://app.votemonitor.org/statistics - 500 error

@jrstrayhorn you have some time to take a look?  It could be a server error.

**Comment by aniri** [comment]
@Botosio It might crash because there are no test data added and there's nothing to display now. I will check.

**Comment by jrstrayhorn** [comment]
@Botosio - sure... I'll check it out too.

**Comment by aniri** [comment]
@Botosio @jrstrayhorn ok, found the issue and fixed it ;)

Also added some test data so there are some stats shown :D 

You can also use the https://monitorizare-vot-ong-git-develop.code4romania.vercel.app/ as this is a bit more up to date than https://app.votemonitor.org .

As for the updates on statistics, the changes to be made are the following (as there might be some changes between current implementation and design):
- add the 'Active statistics' label above the stats cards
- extract texts in translation files; just copy the current texts for both en and ro and I'll update them :)
- update design for cards
- the values in the tables from the cards are: index, the label and value from the response from the API (we'll have to add the full names instead of initials from the api)
```
"data": [
    {
      "label": "B",
      "value": "1"
    },
    {
      "label": "BH",
      "value": "1"
    },
    {
      "label": "CJ",
      "value": "1"
    }
  ],
```
- the complete list should be shown in a popup instead of a new page

I hope this clears things up a bit, as I noticed that the labels of the cards in the design do not match the ones in the implementation (which are in Romanian now :exploding_head: so probably confusing). Each card matches an API call.

Thanks!

**Comment by Botosio** [comment]
@aniri new UI and dialog, please review code too I removed a lot!
![image](https://user-images.githubusercontent.com/44526601/96718169-9cefe180-1375-11eb-91d8-1f9d9776770d.png)
![image](https://user-images.githubusercontent.com/44526601/96718176-a11bff00-1375-11eb-8508-679127e691c7.png)
