### ISSUE TITLE
Enhance add form with predefined options functionality

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#291]
Please see the UI for this here https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=754%3A0 , under `Predefined options`

- The predefined answer options should be defined in a config file. Please add some test options for start :smiley: 
- If these are available, a new link should be displayed in the form, under the questions `+ Choose predefined options`.
- Show the list of options from the config file.
- The user can choose any of the options. The selection will be stored for future use and the selected options will be added to the form.

_Please use bootstrap classes as much as possible and avoid adding custom css styles to keep the codebase clean & consistent._

_Also, make sure all texts are extracted in translation files._

**Comment by VladCuciureanu** [comment]
In progress.
