### ISSUE TITLE
[Observers] Call delete endpoint from observers list

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#293]
The delete observer action is available in the observers lists, in the action dropdown. When pressed it should show a confirmation dialog and if the user confirms the action, the delete should be called `DELETE ​/api​/v1​/observer`

This is very similar to the delete functionality from the edit observer page. Please check that out.

**Comment by VladCuciureanu** [comment]
@aniri Could I maybe get assigned to this?

**Comment by RaduCStefanescu** [comment]
All yours @VladCuciureanu
