### ISSUE TITLE
[Statistics] Adjust statistics cards headers

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#294]
The statistics card titles need a bit of updates:

- they are now made up of header + subheader and they should just be one line of text
- the texts for them should also be translatable and extracted in the translation files. You can use the romanian texts in the en transalation files, as we'll adjust the translations later :)

**Comment by aniri** [comment]
in progress @Botosio

**Comment by aniri** [comment]
hey @Botosio :smiley: any updates on this?

**Comment by Botosio** [comment]
oops sorry missed this, I can take a look

**Comment by Botosio** [comment]
so the header and sub-header comes back from the API.  So the translations I would think would be in the backend.
![image](https://user-images.githubusercontent.com/44526601/98810042-8d9c0b00-23ec-11eb-9490-bd05ae01d501.png)
it's on 1 line now too.

Is there anything else?

**Comment by aniri** [comment]
@Botosio thanks! looks perfect now! Can you just also remove the `-` between the values?

**Comment by Botosio** [comment]
done

**Comment by aniri** [comment]
@Botosio awesome, thanks!!
