### ISSUE TITLE
[BUG] Incorrect polling station info displayed in details screen

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#310]
- Go to answers
- Pick one answers and open the details screen
- Go back to the answers page
- Pick another answer from the list and open the details screen
- Notice that on the top of the details page, the info about the previous polling station in displayed, instead of the info on the currently selected station

![Screenshot from 2020-11-30 17-53-41](https://user-images.githubusercontent.com/1358055/100632200-39be7b00-3335-11eb-971f-22abe6099dbb.png)

**Comment by GabrielMajeri** [comment]
I'd like to work on this!

**Comment by GabrielMajeri** [comment]
I've investigated this bug, but it seems it might be a non-problem :thinking: 

[The code for the details page](https://github.com/code4romania/monitorizare-vot-ong/blob/develop/src/app/answers/answer-details/answer-details.component.ts#L50) selects the answers based only on the observer's ID (it ignores which polling station you select in the UI).

In the staging environment, we have the same observer with multiple polling stations, but is it possible for this situation to occur in practice? To have the same person be an observer in different polling places?

**Comment by aniri** [comment]
@GabrielMajeri yep, the situation is possible. an observer can visit one or more polling stations. so it seems there's the flaw in the implementation
