### ISSUE TITLE
[BUG] Video attachments are not displayed for notes

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#316]
Go to answers, choose a set of answers with notes with video attachments, go to the notes tab and click on the note.

The video attachments should be displayed in the popup.

**Comment by jrstrayhorn** [comment]
I'd like to work on this one.  

@aniri - is there a user/scenario in the staging environment that shows the buggy behavior?  I don't see any answers with the test user.  I'll try to set this up too but maybe faster if this is already setup somewhere.  Thanks!!

**Comment by aniri** [comment]
@jrstrayhorn thanks for your help! I added some test data in that account. There is one answer now, with two notes, one with an image and one with a video. The one with the image is loaded well, the other not.
