### ISSUE TITLE
Export the data as per-station observation to make analysis easier

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-ong#32]
Our data team has said that pivoting every time the RawResults xlsx available on https://code4.ro/en/project/monitorizare-vot/ is too much work. They would need a csv export with:
- [x] each row is an observation (one polling station, one observer)
- [x] each column is a question/answer (along all forms)
- [ ] export notes together with answers (to be clarified how)

**Comment by KrzysztofMadejski** [comment]
I've prepared a huge pivot query that is doing that. Our data analyst was very happy with the result. I'd be happy to code that in. Maybe as a SQL procedure.

The question is how should it be coded? @bvizureanu ? I'd put that into the API and the dashboard would just call the endpoint to get the data and form it accordingly (html, xlsx, csv or some other format). But that 's a bigger question where reporting logic should be placed. If it will be placed in API other clients could use it as well.

**Comment by KrzysztofMadejski** [comment]
Here are the results of this export: https://github.com/epforgpl/monitorizare-vot-deploy-poland2018/tree/master/results

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
