### ISSUE TITLE
Add one more export button in the answers page

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#321]
Add another export button, to the right of the existing one.

Text: Exporta notele

Url: `GET ​/api​/v1​/export​/all/notes`

![Screenshot from 2020-12-02 19-51-23](https://user-images.githubusercontent.com/1358055/100911373-cdc84800-34d7-11eb-90d2-fbeae36eba14.png)

**Comment by nicolaes** [comment]
Starting work on this.
