### ISSUE TITLE
[BUG] Free text answers are not displayed in admin

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#323]
Go to answers page -> pick one set of answers -> browse throw them and find a question with a free text answer (text area). The answer is not filled in.

Test data:
- observer 0700000001, section SB1
- form deschidere -> question d2.1
- form numarare -> question c2.1

The answers are returned by the API

![Screenshot from 2020-12-02 21-52-03](https://user-images.githubusercontent.com/1358055/100924347-29e79800-34e9-11eb-8865-e7dcb1bc7f7a.png)

**Comment by nicolaes** [comment]
Started work here.
