### ISSUE TITLE
Improve page numbers display

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#328]
Please show the middle pages as ... :smile: 

Also, could we set the default page size to the same number for the whole app? And set it somewhere as a config?

![Screenshot from 2020-12-06 20-19-58](https://user-images.githubusercontent.com/1358055/101289273-1b102680-3804-11eb-9cf2-8a46650db71d.png)

**Comment by nicolaes** [comment]
Taking this
