### ISSUE TITLE
Show error popups with the errors returned by the API when deleting observers

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#333]
Currently the errors returned by the API when trying to delete observers (for example the one when trying to delete observers that filled in some answers) are not displayed.

**Comment by jrstrayhorn** [comment]
I can take a look at this one!

**Comment by aniri** [comment]
hey @jrstrayhorn and welcome back! :D It would be great of you could take this issue. Thanks a lot!! There were a few improvement ideas that came up after we used the app the last time :D 

If I remember well, you also contributed on the backend api :D We also have another project which is in a bigger need of volunteers than this one, so in case you are interested, I'll leave a few links here:
https://github.com/code4romania/de-urgenta-backend/issues/142
https://github.com/code4romania/de-urgenta-backend/issues/141
https://github.com/code4romania/de-urgenta-backend/issues/96

**Comment by aniri** [comment]
Btw, we used this app a bit after the last hacktoberfest and it was a huge improvement from it's previous version :D It's a lot more user friendly now and the feedback was great :D A huge thanks for all your help! 🤗

**Comment by jrstrayhorn** [comment]
That is great to hear!! I'm glad I was able to help.. I'll also take a look at that other repo as well!!

**Comment by jrstrayhorn** [comment]
@aniri is there a user in QA environment that has rights to delete an observer?  I'm using test/test2021 to login and getting a 403 error when trying to delete an observer.

Also, how do I setup the scenario in question? 
1. Create a new observer
2. Login as the new observer and answer questions.
3. Login as an admin with rights to delete observer
4. Try to delete the new observer (at this point should I get the API error??)

Thanks!!

**Comment by aniri** [comment]
hey @jrstrayhorn 

I adjusted the admin rights a bit and added some observers and answers :D 
![image](https://user-images.githubusercontent.com/1358055/138310540-f04bc80b-a629-4fc0-ab31-67f7105fa2c1.png)

- test4 has answers added and should not be deleted <- an api error is returned in this case but not displayed, it should also be displayed
- test5 & test6 do not have answers

I hope these are enough for testing. If not, I'll add more. The observers fil in answers using the mobile app and I have it installed and can easily add answers. This could be done also from swagger, but it's trickier.
