### ISSUE TITLE
Redirect to forms list after saving a new form draft or publishing a new form

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#337]
Go to /forms
Fill in some data
Click the button for saving a draft form / publishing the form
**After a successful result from the save action, redirect to the forms list**

**Comment by Botosio** [comment]
I can take a look at this.

**Comment by Botosio** [comment]
@aniri for the QA setup, can I use a temporary username and password?  I'm trying to just run locally.

**Comment by aniri** [comment]
> @aniri for the QA setup, can I use a temporary username and password? I'm trying to just run locally.

hey @Botosio and welcome back! 🥳 

you can use the test account:
```
{
  "user": "test",
  "password": "test2021"
}
```

**Comment by Botosio** [comment]
@aniri ha, thanks I didn't know if you would remember or not.  I'm running late on my Hactoberfest this year.  Trying to pick up a couple of stories.  Hope everything is going well.

**Comment by aniri** [comment]
@Botosio Yep, I remember :D And I'm good, I hope you are too!

>  I'm running late on my Hactoberfest this year.

Uh, oh! After we used the app in december last year, I added some issues for small improvements ;)

**Comment by aniri** [comment]
Btw, we used this app a bit after the last hacktoberfest and it was a huge improvement from it's previous version :D It's a lot more user friendly now and the feedback was great :D A huge thanks for all your help! 🤗

**Comment by Botosio** [comment]
@aniri so I have this working and you get redirected back to the list, however some other process is killing the app...
I'm still looking into it but after a save and I see the Post API call, the application becomes non-responsive.

Does this happen to you?

**Comment by Botosio** [comment]
@aniri Can we create an issue about after you submit on the forms page (publish or draft) the application hangs and then crashes.  This is now blocking this PR.

@jrstrayhorn  can confirm, happens on his local also.

**Comment by aniri** [comment]
hey @Botosio the same happens for me :( I will open the issue. I'll keep this PR open until the crash is also fixed in another PR, but the redirect part looks good 🚀

**Comment by Botosio** [comment]
I'm getting a 400 post error now, I saw a PR that might have fixed it and wanted to test but no luck.
@aniri

**Comment by idormenco** [comment]
@Botosio make sure that you use unique form code when creating a form. Unique to previously created forms

**Comment by Botosio** [comment]
> @Botosio make sure that you use unique form code when creating a form. Unique to previously created forms

@idormenco Got it, thank you!  Is there a feature to display an error when validation doesn't pass?

**Comment by idormenco** [comment]
hmmm ,don't think so. We could add one. 
@aniri please advice

**Comment by aniri** [comment]
Yep, we should display the error in case the code is not unique. The validation was just implemented on the backend, so we'll have to add an issue for displaying the error message :D

**Comment by idormenco** [comment]
@aniri I will create an issue

**Comment by idormenco** [comment]
please see #359 and #360
