### ISSUE TITLE
[BUG] Application freezes after adding a new form

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#355]
Steps to reproduce:
- go to forms list
- add a new draft form
- after you submit on the forms page (publish or draft) the application hangs and then crashes

**Comment by idormenco** [comment]
@aniri I will investigate

**Comment by aniri** [comment]
@idormenco you can easily check from this PR https://github.com/code4romania/monitorizare-vot-ong/pull/353
