### ISSUE TITLE
Add form validation

### ISSUE THREAD

**Issue by idormenco** [code4romania/monitorizare-vot-ong#360]
A user can click `Save as draft` and `Publish form` with empty fields.
Add form validation

**Comment by Botosio** [comment]
I can take a look.

**Comment by idormenco** [comment]
all yours

**Comment by Botosio** [comment]
@idormenco I feel like these should be required?
![image](https://user-images.githubusercontent.com/44526601/138868955-fc90ab88-23dd-4863-bc74-65bc74851fc3.png)

Maybe not diaspora.

Thoughts?

**Comment by Botosio** [comment]
Oh no, the description is used on 2 inputs.
Is one supposed to be title?  Is there a swagger document?

![image](https://user-images.githubusercontent.com/44526601/138869377-6c4528c4-c4a2-4de8-8662-9b8171596382.png)

**Comment by idormenco** [comment]
@Botosio yes we do have a swagger [here ](https://api.votemonitor.org/swagger/index.html). But I think we do not enforce any rules on the server-side for this endpoint. 
I think we should also validate on the server-side. ~Hello from the server-side~

For now please do not allow creating forms with empty fields

**Comment by Botosio** [comment]
@aniri it looks like the frontend and backend do not match.
New story for the backend to add "title"?

![image](https://user-images.githubusercontent.com/44526601/138871341-3ca432be-c173-4f10-b253-e6386c1f4cdc.png)

**Comment by idormenco** [comment]
@Botosio just send it in request and I will handle this in the API

**Comment by Botosio** [comment]
> @Botosio just send it in request and I will handle this in the API

Sounds good, calling it just "title": string.
