### ISSUE TITLE
Feat: filter reports by specific observer, district or polling station

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-ong#48]

**Comment by RaduCStefanescu** [comment]
This feature is currently being implemented.
Check out: 
https://github.com/code4romania/monitorizare-vot-ong/issues/110
https://github.com/code4romania/monitorizare-vot-ong/issues/109
https://github.com/code4romania/monitorizare-vot-ong/issues/108
