### ISSUE TITLE
Punere in picioare baza locala

### ISSUE THREAD

**Issue by stochris** [code4romania/monitorizare-vot-ong#5]
Guys, aveti idee ce sa fac ca sa rulez proiectul local ? 

Eroare pe care o primesc `Format of the initialization string does not conform to specification starting at index 0.` in `RaspunsuriQueryHandler` la linia 26, variabila `sectiiCuObservatori` are pe `Results Views` o expectie cu acest mesaj

**Comment by dhont** [comment]
Iti trebuie un connection string in appsettings.json. Ca alternativa ai
putea folosi Api-ul din Azure?

**Comment by stochris** [comment]
Saddly, nu. Vreau sa fac ceva la autentificare :).
Oricum, daca trebuie connString, ma descurc de aici. Mersi mult!
