### ISSUE TITLE
Interface to define forms

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-ong#51]
Would be very cool and allow observer core team to see how will it look in the app. Are some questions not mandatory. Is it better to frame sth as a seprate question, as a extra answer within the options or as an ask to add a note.

- [ ] define forms
- [ ] export forms in Word document (so paper forms can be handed-in as well to observers that will correspond 1-to-1 to app forms)

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
