### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-ong#52]
- [ ] map where are observers
- [ ] map with metrics overlayed over administrative boundaries
- [ ] status of forms filled and notes count by each observer / team
- [ ] simple pie charts for each questions
- [ ] temporal reports: see what commissions have started counting at which hour, how long did it take, etc.
- [ ] total amount spend observing
- [ ] number of active observers / total observers

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
