### ISSUE TITLE
Annotate notes

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-ong#54]
Problem: Notes are not possible to process automatically. To make sense of them they need to be somehow processed for further analysis. Our analysts (2 of them) were going through all the notes tagging them. As they have been working on semi-incremental exports they might have analyse same notes twice. It was also hard to then analyze those notes in total.

I propose to move this annotation process into the platform. That would look as following:
- [ ] notifications / list of new unprocessed notes
- [ ] possibly filtering nodes by modulo of number of people analyzing them so same note won't be processed by many people
- [ ] each note will be shown with photo / video next to it  and also the linked question and answer
- [ ] analysts will be able to add free-form tags to each note
- [ ] while adding tags the ones already existing will be auto-suggested
- [ ] list of all the notes filtered by question, tag, person/team
- [ ] nice-to-have: ability to merge tags
- [ ] simple statistics based on tags, questions, polling stations

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
