### ISSUE TITLE
Coordinators

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-ong#55]
Have in the system the concept of coordinators who are taking care of group of observers/teams
- coordinators could pass on observers between themselves (group of observers)
- what's app invite link to the group between coordinator and an observer/team so another person can step in 
- [ ] dashboard of a coordinator
  - all their observers / teams
  - where are they

**Comment by RaduCStefanescu** [comment]
Issue added in features of new version of the app.
