### ISSUE TITLE
[Create and edit forms] List available forms

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#59]
API

- add  a call to retrieve available forms
- add call info in [swagger docs](https://monitorizarevotong.azurewebsites.net/swagger/ui/index.html) 

Frontend

- display available forms
- for each form display code, name and action buttons for viewing, editing and deleting a form
- screen mockups available here: http://bit.ly/2L0tNG2

Best practices

- codebase language should be English
- we :two_hearts: unit tests

------------------------------------------------------------------------------------------------------
- [ ] API subtask: create a new API endpoint /api/v1/formulare/meta that return the name of the available form (form code), the description (form description) and if the form is completed or draft (form completed flag)
- [ ] Frontend subtask: display the available forms, their state and actions pertaining for each form, as per the screen mockups

![Form set page](https://user-images.githubusercontent.com/15039873/56458361-483d6600-638e-11e9-88a5-5c5517c4a765.png)

**Comment by RaduCStefanescu** [comment]
In progress @ Bogdan Teslarasu (FE) & Bogdan Bujdea (BE)

**Comment by aniri** [comment]
new UI available here https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=754%3A0
