### ISSUE TITLE
[Create and edit forms] Add new form

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#60]
API

- add a call to add a new form
- add call info in [swagger docs](https://monitorizarevotong.azurewebsites.net/swagger/ui/index.html) 

Frontend

- display a button in the form set screen for adding a new form
- implement screen for adding the information about the new form
- a form can contain multiple types of questions 
- here is a link to the real forms for real examples of questions and types of questions https://docs.google.com/spreadsheets/d/1kAhpqSu0bhEfxH0l0nWTOX0AlPcK_VXQbuDsj35WzL8/edit#gid=0
- screen mockups available here: http://bit.ly/2L0tNG2

Best practices

- codebase language should be English
- we :two_hearts: unit tests

------------------------------------------------------------------------------------------------------
- [ ] API task - add a POST to formular API to save a new form in the backend
- [ ] Frontend task - add a new page for creating and saving a form

![Create form - add new form](https://user-images.githubusercontent.com/15039873/56458385-92bee280-638e-11e9-8035-d440cc360bb8.png)

**Comment by RaduCStefanescu** [comment]
API in progress @lrdTnc

**Comment by RaduCStefanescu** [comment]
Frontend in progress @ Bogdan Tasalarasu
