### ISSUE TITLE
[Manage observers] View observers list

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#66]
API

- add a call to retrieve available observers
- add call info in [swagger docs](https://monitorizarevotong.azurewebsites.net/swagger/ui/index.html) 

Frontend

- display available observers

Best practices

- codebase language should be English
- we :two_hearts: unit tests

- [ ] FE: Implement an observer panel where an admin user can view all observers in the platoform
- [ ] FE: Implement drilldown view to a single observer
- [ ] BE: Enhance observer controller to return a list with all the observer resources in the platform

**Comment by RaduCStefanescu** [comment]
In progress @ Marius Stanescu

**Comment by shurub3l** [comment]
Only doing backend

**Comment by shurub3l** [comment]
Question: Can I organize the folders by feature? (https://msdn.microsoft.com/en-us/magazine/mt763233.aspx). It's pretty difficult to find what you're looking for.

**Comment by RaduCStefanescu** [comment]
> Question: Can I organize the folders by feature? (https://msdn.microsoft.com/en-us/magazine/mt763233.aspx). Now, it's pretty difficult to find what you're looking for when working on something. You have to open about 5 separate folders.

@bvizureanu ?

**Comment by vcondratiev** [comment]
I will be working on the frontend side.

**Comment by RaduCStefanescu** [comment]
Handled in #143
