### ISSUE TITLE
[Manage observers] Search through observers list

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#68]
API

- enhance call to search through observers list
- add call info in [swagger docs](https://monitorizarevotong.azurewebsites.net/swagger/ui/index.html) 

Frontend

- search box for observers
- display search results

Best practices

- codebase language should be English
- we :two_hearts: unit tests
Tasks:
- [ ] FE: Add search text box for searching observers based on name, surname, telephone number
- [ ] BE: Enhance observer controller to filter observers based on name, surname,  telephone number

**Comment by RaduCStefanescu** [comment]
issue handled in #143
