### ISSUE TITLE
[Manage observers] Add new observer

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#69]
The add observer form should contain:

- full name
- phone number
- email address
- city
- locality
- polling station

API

- add a call to add a new observer
- add call info in [swagger docs](https://monitorizarevotong.azurewebsites.net/swagger/ui/index.html) 

Frontend

- display a button in the observers list screen for adding a new observer
- implement screen for adding the information about the new observer

Best practices

- codebase language should be English
- we :two_hearts: unit tests
Tasks:
- [ ] FE: Enhance observers panel with functionaliy for adding a single observer 
- [ ] BE: Enhance observer controller to accept a single request for creating a new resource

**Comment by RaduCStefanescu** [comment]
In progress @ Alexandru Alin Tudor

**Comment by RaduCStefanescu** [comment]
Handled in #143
