### ISSUE TITLE
[Manage observers] Edit observers

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#70]
API

- add a call to update information about an observer
- add call info in [swagger docs](https://monitorizarevotong.azurewebsites.net/swagger/ui/index.html) 

Frontend

- navigation to edit observer screen
- implement screen for editing observer data

Best practices

- codebase language should be English
- we :two_hearts: unit tests
Tasks:
- [ ] FE: Implement edit functionality on Observers panel
- [ ] BE: Enhance Observers controller to accept PUT requests for observer resource

**Comment by RaduCStefanescu** [comment]
Handled in #143
