### ISSUE TITLE
[Manage observers] Delete observers

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#75]
API

- add a call to delete an observer
- add call info in [swagger docs](https://monitorizarevotong.azurewebsites.net/swagger/ui/index.html) 

Frontend

- button that allows me to delete an observer
- on click a pop-up message appears asking for action confirmation
- the action does not delete that observer's app data if he already filled in answers

Best practices

- codebase language should be English
- we :two_hearts: unit tests

Tasks:
- [ ] FE: Implement delete feature on observers screen
- [ ] BE: Enhance Observer controller to accept DELETE operation on observer resource

**Comment by RaduCStefanescu** [comment]
handled in #143
