### ISSUE TITLE
[Create and edit forms] View list of form sets

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#76]
API

- add a call to retrieve available form sets
- add call info in [swagger docs](https://monitorizarevotong.azurewebsites.net/swagger/ui/index.html) 

Frontend

- display available form sets
- screen mockups available here: http://bit.ly/2L0tNG2

Best practices

- codebase language should be English
- we :two_hearts: unit tests

Tasks:
- [ ] FE: create new screen to view all the forms in the platform
- [ ] BE: enhance forms controller to retrieve all forms in platform

**Comment by RaduCStefanescu** [comment]
In progress @ Bogdan Teslarasu
