### ISSUE TITLE
Highlight red flags number next to form

### ISSUE THREAD

**Issue by KrzysztofMadejski** [code4romania/monitorizare-vot-ong#78]
On this mockup: https://www.figma.com/proto/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=3%3A94&scaling=min-zoom&redirected=1

Next to each form (A, B, C) there should be number of red flagged questions so moderator can quickly see where is the problem. Opening flagged observation should go straight to the first form that contain red flags (skip forms without redflags)

CC @aniri

**Comment by RaduCStefanescu** [comment]
Issue handled in new UX redesign.
Backed up in MV2.0 document.
