### ISSUE TITLE
[Manage observers] Upload a CSV file containing details of the observers

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-ong#80]
The API needs to be enhanced with an endpoint that receives a CSV file containing observer details.

The observer details should be the following:
- full name (optional)
- phone number (mandatory)
- email address (optional)
- city (optional)
- locality (optional)
- polling station (optional)

The API will return all the rows that are invalid and were not saved.

The Observers page needs to be enhanced with a form for uploading a CSV file, a button next to Add Observer to 
Tasks:
- [ ] FE: Add upload feature to Observers panel
- [ ] BE: Enhance observer controller to accept a CSV file, transform contents to Observer objects and return all rows that were not saved

**Comment by KrzysztofMadejski** [comment]
What fields are required? Is phone & email needed? Or only "login" would suffice which can take any form..?

How city is different from locality? Remember than for example in Poland we have several administrative levels https://github.com/code4romania/monitorizare-vot/issues/68

**Comment by RaduCStefanescu** [comment]
> What fields are required? Is phone & email needed? Or only "login" would suffice which can take any form..?
> 
> How city is different from locality? Remember than for example in Poland we have several administrative levels [code4romania/monitorizare-vot#68](https://github.com/code4romania/monitorizare-vot/issues/68)

Good points @KrzysztofMadejski updated with additional information. Please be aware, this only addresses the may release for Romania. In a future enhancement, the datamodel for Observer will be defined from API - you can define whatever fields you want/need to create an Observer.

**Comment by RaduCStefanescu** [comment]
Can be closed, handled in #143
