### ISSUE TITLE
[Reports] Download all answers in the database

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/monitorizare-vot-ong#87]
On the admin panel of NGO admin app, we need to have a download button that returns a CSV file with all the answers in the platform.

**Comment by KrzysztofMadejski** [comment]
Our data ppl were asking for a flat structure: one observation (all answers) in one row. I had SQL for that, but it seems I accidentally deleted that. :/

**Comment by aniri** [comment]
you can see the export button in the new UI https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=754%3A0

depends on https://github.com/code4romania/monitorizare-vot-ong/issues/209

**Comment by aniri** [comment]
closing this as a download button was implemented. maybe we could add a separate issue for a different download format if it will be needed in the future :smiley:
