### ISSUE TITLE
[View responses] View only emergencies

### ISSUE THREAD

**Issue by aniri** [code4romania/monitorizare-vot-ong#91]
Update 'emergencies' page to only show flagged questions that have been answered.

- screen mockups available here: https://www.figma.com/file/61NHR7fwmV1Dsv4Pb6F8T7/code4ro_mv_user-management_2018.04.21-(Copy)?node-id=754%3A0

Please use bootstrap classes as much as possible and avoid adding custom css styles to keep the codebase clean & consistent. The new UI should be as similar as possible to the one in figma, not pixel perfect.

Also, make sure all texts are extracted in translation files.

**Comment by florinrusu96** [comment]
Hello!

I will look into this one.

**Comment by aniri** [comment]
moving back in todo as it was idle for a long time
